id: I40D5D4F0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:26:33+00:00'
last_modified: '2022-06-08T14:19:41.986659+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18172
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་བསྟོད་སྤྲིན་གྱི་སྒྲ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF32:
      image_group_id: I1KG18216
      title: ''
      total_pages: 298
      order: 1
      base_file: BF32.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
