id: P010536
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:54:48.600966
source_metadata:
  id: bdr:W1KG18172
  title: འཇམ་དཔལ་མཚན་བརྗོད་ཀྱི་འགྲེལ་པ་བསྟོད་སྤྲིན་གྱི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    9373e4cb1fc644f5bed819228884360d:
      image_group_id: I1KG18216
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
